### PR TITLE
SideNavigation and FireCenterDropdown UI tweaks

### LINKED ISSUE #5298: ASA Go: UI issues when soft nav buttons present
**Actual Behaviour**

The login button on the landing screen can be hidden/covered by the soft navigation buttons on some devices (eg. Samsung Galaxy S24).

**Steps To Reproduce**

1. ...
2. 
3. 

**Screenshots**

**Expected Behaviour**

### PR DESCRIPTION
**Pull request by dgboss**
I noticed that on phones with persistent soft navigation buttons the `SideNavigation` gets covered in landscape orientation.
image

This PR adds safe areas inset padding to the left. Note that this also bumps the buttons out to prevent overlap with a camera island.

This PR also adjusts the height of the `FireCenterDropdown` to match the height of the `TodayTomorrowSwitch` as per Figma designs. iOS seemed to match heights before but Android didn't. 

Closes: #5298 

# Test Links:
[Landing Page](https://wps-pr-5300-e1e498-dev.apps.silver.devops.gov.bc.ca/)
[MoreCast](https://wps-pr-5300-e1e498-dev.apps.silver.devops.gov.bc.ca/morecast)
[Percentile Calculator](https://wps-pr-5300-e1e498-dev.apps.silver.devops.gov.bc.ca/percentile-calculator)
[C-Haines](https://wps-pr-5300-e1e498-dev.apps.silver.devops.gov.bc.ca/c-haines)
[FireCalc](https://wps-pr-5300-e1e498-dev.apps.silver.devops.gov.bc.ca/fire-behaviour-calculator)
[FireCalc bookmark](https://wps-pr-5300-e1e498-dev.apps.silver.devops.gov.bc.ca/fire-behaviour-calculator?s=266&f=c5&c=NaN&w=20,s=286&f=c7&c=NaN&w=16,s=1055&f=c7&c=NaN&w=NaN,s=305&f=c7&c=NaN&w=NaN,s=344&f=c5&c=NaN&w=NaN,s=346&f=c7&c=NaN&w=NaN,s=328&f=c7&c=NaN&w=NaN,s=1399&f=c7&c=NaN&w=NaN,s=334&f=c7&c=NaN&w=NaN,s=1082&f=c3&c=NaN&w=NaN,s=388&f=c7&c=NaN&w=NaN,s=309&f=c7&c=NaN&w=16,s=306&f=c7&c=NaN&w=NaN,s=1029&f=c7&c=NaN&w=NaN,s=298&f=c7&c=NaN&w=NaN,s=836&f=c7&c=NaN&w=NaN,s=9999&f=c7&c=NaN&w=NaN)
[Auto Spatial Advisory (ASA)](https://wps-pr-5300-e1e498-dev.apps.silver.devops.gov.bc.ca/auto-spatial-advisory)
[HFI Calculator](https://wps-pr-5300-e1e498-dev.apps.silver.devops.gov.bc.ca/hfi-calculator)
[SFMS Insights](https://wps-pr-5300-e1e498-dev.apps.silver.devops.gov.bc.ca/insights)
[Fire Watch](https://wps-pr-5300-e1e498-dev.apps.silver.devops.gov.bc.ca/fire-watch)
[Weather Toolkit](https://wps-pr-5300-e1e498-dev.apps.silver.devops.gov.bc.ca/weather-toolkit)

### CODE REVIEW

File: mobile/asa-go/src/components/FireCenterDropdown.tsx [hunk 1]
```diff
@@ -38,7 +39,11 @@ const FireCenterDropdown = ({
   };
 
   return (
-    <FormControl variant="outlined" size="small" sx={{ minWidth: 175 }}>
+    <FormControl
+      variant="outlined"
+      size="small"
+      sx={{ minWidth: 175, height: BUTTON_HEIGHT - 2 }}
```
Comment (conbrad) [inline mobile/asa-go/src/components/FireCenterDropdown.tsx]: Looks like only this component uses `BUTTON_HEIGHT`, can we just subtract 2 from the constant itself?

**Review by brettedw — APPROVED** [review]
Thanks for cleaning that up!

File: mobile/asa-go/src/components/FireCenterDropdown.tsx (hunk 1 above)
Comment (dgboss) [reply mobile/asa-go/src/components/FireCenterDropdown.tsx]: `MapIconButton` also uses `BUTTON_HEIGHT` and `TodayTomorrowSwitch` used it -2px as well. I changed all components to use the constant without subtracting the 2px and think it still looks good.
https://github.com/bcgov/wps/pull/5300/changes/1d3f0eb7f5969a6eae664c965749f642da957c0d

**Review by conbrad — APPROVED** [review]
🔥
